replicaCount: 1

image:
  repository: marcoglorioso/efk-demo-service-b
  tag: 1.0.0
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  name: efk-demo-service-b

app:
  name: efk-demo-app-b

resources: {}