apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic   # You can change this to any namespace you're using
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.10.1  # Change this if you want a different version
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"  # Adjust this to match your Elasticsearch service
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic  # Same namespace as the deployment
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: elastic  # Same namespace as the deployment
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30001
  type: NodePort